version: '2.2'

services:

  interview-localstack:
    image: localstack/localstack:4.14.0
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=ap-south-1
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  
  interview-postgres:
    image: "postgres:14"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trips
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
